# KAFKA SETTINGS
KAFKA_HOST = 'localhost:9092'
KAFKA_SOURCE_TOPIC = 'urls'
KAFKA_RESULT_TOPIC = 'results'
KAFKA_CONSUMER_GROUP = 'parser'

# MONGO SETTINGS
MONGODB_SERVER = "localhost"
MONGODB_PORT = 27017
MONGODB_DB = "Tutorial"
MONGODB_COLLECTION_RESULT = "results"
